spring:
   data:
     elasticsearch:
     #cluster-name: #默认为elasticsearch
       cluster-nodes: 127.0.0.1:9300
   thymeleaf:
     prefix: classpath:/templates/
     suffix: .html
     mode: html
     cache: false