spring:
   servlet:
     multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 30MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 100MB

   data:
     elasticsearch:
     #cluster-name: #默认为elasticsearch
       cluster-nodes: 127.0.0.1:9300
   thymeleaf:
     prefix: classpath:/templates/
     suffix: .html
     mode: html
     cache: false